version: 1.0.{build}
image: Visual Studio 2017
configuration: Release

before_build:
- appveyor-retry dotnet restore ConsoleWalker.sln

build_script:
- dotnet publish ConsoleWalker -o artifacts -c %CONFIGURATION% /p:Version=%APPVEYOR_BUILD_VERSION%

after_build:
 - 7z a artifacts\ConsoleWalker.zip %APPVEYOR_BUILD_FOLDER%\ConsoleWalker\artifacts\*

artifacts:
- path: artifacts\**\*
