version: 1.0.{build}
image: Visual Studio 2017
configuration: Release

build_script:
- dotnet publish ConsoleWalker -o ../artifacts -c %CONFIGURATION% /p:Version=%APPVEYOR_BUILD_VERSION%

artifacts:
- path: artifacts\**\*
